import { Post, Comment, User } from './types';

export const mockUsers: User[] = [
  { id: '1', studentId: 'STU001', name: 'Rahul Sharma', email: 'rahul@college.edu', role: 'student' },
  { id: '2', studentId: 'STU002', name: 'Priya Patel', email: 'priya@college.edu', role: 'student' },
  { id: '3', studentId: 'STU003', name: 'Amit Kumar', email: 'amit@college.edu', role: 'student' },
  { id: '4', studentId: 'ADMIN001', name: 'Dr. Principal', email: 'principal@college.edu', role: 'admin' },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'Library needs extended hours during exams',
    description: 'The library currently closes at 6 PM, but during exam season, students need a quiet place to study late into the night. Requesting library hours to be extended until 11 PM during exam weeks.',
    category: 'academic',
    visibility: 'public',
    authorId: '1',
    authorName: 'Rahul Sharma',
    upvotes: 127,
    hasUpvoted: false,
    commentsCount: 23,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'WiFi connectivity issues in Hostel Block B',
    description: 'For the past two weeks, the WiFi in Block B has been extremely slow and frequently disconnects. This is affecting our ability to attend online classes and submit assignments.',
    category: 'infrastructure',
    visibility: 'public',
    authorId: '2',
    authorName: 'Priya Patel',
    upvotes: 89,
    hasUpvoted: true,
    commentsCount: 15,
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    title: 'Canteen food quality has declined',
    description: 'The quality of food in the main canteen has significantly declined in the past month. The food is often cold and portions have become smaller while prices remain the same.',
    category: 'food',
    visibility: 'private',
    authorId: '3',
    authorName: 'Anonymous',
    upvotes: 156,
    hasUpvoted: false,
    commentsCount: 42,
    createdAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    title: 'Request for more water coolers in hostels',
    description: 'There is only one water cooler per floor which creates long queues during peak hours. Request installation of additional water coolers on each floor.',
    category: 'hostel',
    visibility: 'public',
    authorId: '1',
    authorName: 'Rahul Sharma',
    upvotes: 67,
    hasUpvoted: false,
    commentsCount: 8,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    title: 'Need better lab equipment for Electronics department',
    description: 'Many oscilloscopes and multimeters in the electronics lab are outdated or non-functional. This severely impacts our practical learning experience.',
    category: 'academic',
    visibility: 'public',
    authorId: '2',
    authorName: 'Priya Patel',
    upvotes: 45,
    hasUpvoted: false,
    commentsCount: 12,
    createdAt: new Date('2024-01-10'),
  },
];

export const mockComments: Comment[] = [
  {
    id: '1',
    postId: '1',
    authorId: '2',
    authorName: 'Priya Patel',
    content: 'Completely agree! Last semester I had to study in the corridor because the library was closed.',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    postId: '1',
    authorId: '3',
    authorName: 'Amit Kumar',
    content: 'Even 10 PM would be helpful. The hostel common rooms are too noisy.',
    createdAt: new Date('2024-01-15'),
  },
];
